### ISSUE TITLE
nao_speech.pyのエラー

### ISSUE THREAD

**Issue by kochigami** [kochigami/aldebaran_robot_ws#78]
内部でのspeech_recognitionのサービスを呼ぶと、
nao_speech.pyで発生するエラー

```
[ERROR] [WallTime: 1420547520.207193] Error processing request: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 370, in start\n    self.conf )\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 434, in __init__\n    self.reconfigure(config)\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 456, in reconfigure\n    Util.parse_vocabulary( config["vocabulary"].encode(\'utf-8\') ),\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)\n"]
[ERROR] [WallTime: 1420547535.216344] Speech recognition was not started
[ERROR] [WallTime: 1420547535.423417] Error processing request: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
['Traceback (most recent call last):\n', '  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 623, in _handle_request\n    response = convert_return_to_response(self.handler(request), self.response_class)\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 370, in start\n    self.conf )\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 434, in __init__\n    self.reconfigure(config)\n', '  File "/home/kochigami/ros/hydro/src/ros-naoqi/nao_robot/nao_apps/nodes/nao_speech.py", line 456, in reconfigure\n    Util.parse_vocabulary( config["vocabulary"].encode(\'utf-8\') ),\n', "UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)\n"]
```

**Comment by kochigami** [comment]
#79に書きます
